---
title: 'Look-alike modelling: using stratified sampling technique'
output:
  html_document:
    df_print: paged
---


```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
library(rmarkdown)
library(patchwork)
set.seed(1234)

# Set directory
setwd("D:/mydocs/blog/posts/lookalike_modelling")

df <- read.csv("cc_data.csv")
df
```


```{r}
# generate html for blog
kable(df[1:10,]) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                full_width = F, font_size = 10) %>%
  row_spec(1:10,bold = T) %>%
  scroll_box(width = "700px", height = "400px")
```



```{r}
# Summary of target group
summary(df[1:1000,])
```


```{r}
# Make bins for chosen variables
df <- df %>% mutate(balance_bin = cut(BALANCE,c(-1,0,100,500,1000,2000,3000,
                                                5000,7000,10000,20000)),
                    purchases_bin = cut(PURCHASES,c(-1,0,100,500,1000,2000,5000,10000,50000)),
                    cashadvance_bin = cut(CASH_ADVANCE,c(-1,0,500,1000,2000,5000,50000)))

df %>% top_n(10) %>% select(CUST_ID,
                    balance_bin,
                    purchases_bin,
                    cashadvance_bin)
```



```{r}
# Make a combined bin
df <- df %>% mutate(combined_bin = paste(balance_bin,
                                         purchases_bin,
                                         cashadvance_bin))

df %>% top_n(10) %>% select(CUST_ID,
                            combined_bin,
                            balance_bin,
                            purchases_bin,
                            cashadvance_bin)

```


```{r}
# Combined distribution of target group:
target_profile <- df[1:500,] %>% group_by(combined_bin) %>%
  summarise(customers=n()) %>%
  mutate(bin_wt = customers/nrow(df[1:500,]))

target_profile %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                full_width = F, font_size = 10) %>%
  row_spec(1:nrow(target_profile),bold = T) %>%
  scroll_box(width = "700px", height = "400px")

```

```{r}
#### Generate lookalikes

control_n = 500 # desired number of customers in the control group
j = 0 # counter
df_control = data.frame() # dataframe where control group will be formed
for (i in target_profile$combined_bin){
  j=j+1 
  print(j)
  df_control_bin <- df[(control_n+1):nrow(df),] %>% filter(combined_bin==i)
  df_control_bin_sample <- sample(1:nrow(df_control_bin),
                            size= as.integer(target_profile %>%
                                               filter(combined_bin==i) %>%
                                               select(bin_wt)*control_n), replace = TRUE)
  df_control_bin_sample <- df_control_bin[df_control_bin_sample,] # pick actual rows from sample index values
  df_control <- rbind(df_control,
                      df_control_bin_sample) # keep adding the main control group
                                              #data frame with each iteration
}

rm(df_control_bin)
rm(df_control_bin_sample)
rm(i)
rm(j)

df_control
n_distinct(df_control$CUST_ID)

```


```{r}
# Distribution of target and control groups
p1 <- df[1:500,] %>%
  ggplot(aes(y=BALANCE)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot(outlier.shape = NA) + 
  scale_y_continuous(breaks=seq(0, 10000, by= 1000))+
  coord_cartesian(ylim=c(0, 10000)) +
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
p2 <- df[1:500,] %>%
  ggplot(aes(y=PURCHASES)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot(outlier.shape = NA) + 
  scale_y_continuous(breaks=seq(0, 5000, by= 1000))+
  coord_cartesian(ylim=c(0, 5000))+
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
p3 <- df[1:500,] %>%
  ggplot(aes(y=CASH_ADVANCE)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot(outlier.shape = NA) + 
  scale_y_continuous(breaks=seq(0, 5000, by= 1000))+
  coord_cartesian(ylim=c(0, 5000))+
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
p4 <- df_control %>%
  ggplot(aes(y=BALANCE)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot(outlier.shape = NA) + 
  scale_y_continuous(breaks=seq(0, 10000, by= 1000))+
  coord_cartesian(ylim=c(0, 10000))+
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
p5 <- df_control %>%
  ggplot(aes(y=PURCHASES)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot(outlier.shape = NA) + 
  scale_y_continuous(breaks=seq(0, 5000, by= 1000))+
  coord_cartesian(ylim=c(0, 5000))+
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())
p6 <- df_control %>%
  ggplot(aes(y=CASH_ADVANCE)) +
  stat_boxplot(geom = "errorbar") +
  geom_boxplot(outlier.shape = NA) + 
  scale_y_continuous(breaks=seq(0, 5000, by= 1000))+
  coord_cartesian(ylim=c(0, 5000))+
  theme(axis.ticks.x = element_blank(), axis.text.x = element_blank())

(p1+p2+p3)/(p4+p5+p6) + plot_annotation(title = 'Top row: Target group, botom row: control group')

```

